### PR TITLE
Lantern Load 1.17 Revision

### PR DESCRIPTION
**Pull request by Luexa**
This pull request makes a few breaking changes to Lantern Load, which are regrettable but correct longstanding flaws in the library. This library was somewhat "forced" into stabilization as AESTD began to use it before it was ready, and other projects followed, hence a few flaws did not have the chance to be fixed before it was too late.

The primary change is that the `load` objective is renamed to `load.status`, as a number of pack authors were unwilling to use this pack with its objective being such a simple name. Now it has a namespace, which should make it more suitable for these cases. This change may seem simple, but it would cause weirdness when combined with the old pack. Hence, this change is intended to be used in 1.17, since packs are incompatible anyway (`pack_format` is now 7 instead of 6, and the changes to world limits will break a lot of assumptions made in previous versions).

Since I had to make this breaking change anyway, I took the opportunity to make some other changes:
 - The initialization function was moved from `load:__init` to `load:_private/init`.
 - `#load:standard` was renamed to `#load:pre_load` to be more general about its intended use (to perform actions before anything is executed in `#load:load`). 
 - The initialization function is now in the tag `#load:_private/init`, and rather than calling `load:__init2`, it expects that future initialization steps will be added to the tag.
 - The tag `#load:__init` is renamed to `#load:_private/load`. This tag first calls `#load:_private/init`, then calls `#load:pre_load`, `#load:load`, and `#load:post_load`.
 - The load tags are now optional so as to allow packs to omit `pre_load` or `post_load` if they do not care to use them (rather than leave them as empty JSON files).
 
I feel these changes overall make Lantern Load feel much more polished, and most importantly a number of people can use the pack who were reluctant to before now that the scoreboard objective is namespaced! Hopefully any future changes will not be necessary, but if they are, the revisions should allow them to be implemented without breaking anything in the future.

### CODE REVIEW

**Comment by Luexa** [comment]
Before merging this pull request, it would be nice to contribute changes to public repositories that use Lantern Load so they don't get blindsided and release a 1.17 version of their pack that uses the outdated revision, which would cause issues when a pack using the newer revision is loaded at the same time. Likely the most well-known usage is that of [Gamemode 4], but a number of other packs use Lantern Load too and I believe a list of the ones available on GitHub has already been compiled. Updating to the new revision of Lantern Load should simply require applying some regex to replace `load` with `load.status`, including the new init functions/tags, and renaming `standard` to `pre_load`.

[Gamemode 4]: https://github.com/Gamemode4Dev/GM4_Datapacks

**Comment by dthigpen** [comment]
Great work, I think these changes are well suited. Additionally, I am interested in what you think the scope and complexity of this datapack should be. The objective based versioning with `load.status` is immensely useful, however I feel like it can be quite verbose, especially with multiple dependencies across several packs. As far as I am aware, each datapack that has dependencies must have something like the following at a minimum,
```mcfunction
# load.mcfunction

# Load new_pack iff dep1, dep2, and dep3 datapacks have correct major/minor versions
scoreboard players set $new_pack load 0 
execute if score $dep1.version.major load matches 0 if score $dep1.version.minor load matches 0.. if score $dep2.version.major load matches 0 if score $dep2.version.minor load matches 0.. if score $dep3.version.major load matches 0 if score $dep3.version.minor load matches 0.. run scoreboard players set $new_pack load 1
execute unless score $new_pack load matches 1 run tellraw @a ["new_pack datapack cannot load, incorrect dependency version found"]

# Set version scores on the load objective since dependencies are satisfied
execute if score $new_pack load matches 1 run scoreboard players set $new_pack.version.major load 1
execute if score $new_pack load matches 1 run scoreboard players set $new_pack.version.minor load 0
execute if score $new_pack load matches 1 run scoreboard players set $new_pack.version.patch load 0

execute if score $new_pack load matches 1 run schedule function new_pack:tick 1t replace
```
This implementation works for well for preventing the datapack from loading without the required dependencies, but it leaves the user without knowing what to do next to troubleshoot. More granular messages can be added to indicate the offending dependencies in the following example,
```mcfunction
# load.mcfunction

# Load new_pack iff dep1, dep2, and dep3 datapacks have correct major/minor versions
scoreboard players set $new_pack load 0

# Check dep1, print missing message
execute if score $dep1.version.major load matches 0 if score $dep1.version.minor load matches 0.. run scoreboard players set $new_pack load 1
execute unless score $dep1.version.major load matches 0.. if score $dep1.version.minor load matches 0.. run tellraw @a ["new_pack expects dep1 v0.0, found v0.0"]
execute if score $dep1.version.major load matches 0 unless score $dep1.version.minor load matches 0.. run tellraw @a ["new_pack expects dep1 v0.0, found v0.0"]

# Check dep2, print missing message
execute if score $dep2.version.major load matches 0 if score $dep2.version.minor load matches 0.. run scoreboard players set $new_pack load 1
execute unless score $dep2.version.major load matches 0.. if score $dep2.version.minor load matches 0.. run tellraw @a ["new_pack expects dep2 v0.0, found v0.0"]
execute if score $dep2.version.major load matches 0 unless score $dep2.version.minor load matches 0.. run tellraw @a ["new_pack expects dep2 v0.0, found v0.0"]

# Check dep3, print missing message
execute if score $dep3.version.major load matches 0 if score $dep3.version.minor load matches 0.. run scoreboard players set $new_pack load 1
execute unless score $dep3.version.major load matches 0.. if score $dep3.version.minor load matches 0.. run tellraw @a ["new_pack expects dep3 v0.0, found v0.0"]
execute if score $dep3.version.major load matches 0 unless score $dep3.version.minor load matches 0.. run tellraw @a ["new_pack expects dep3 v0.0, found v0.0"]

# Set version scores on the load objective since dependencies are satisfied
execute if score $new_pack load matches 1 run scoreboard players set $new_pack.version.major load 1
execute if score $new_pack load matches 1 run scoreboard players set $new_pack.version.minor load 0
execute if score $new_pack load matches 1 run scoreboard players set $new_pack.version.patch load 0

execute if score $new_pack load matches 1 run schedule function new_pack:tick 1t replace
```

This implementation works well, but it is relatively verbose and quite a manual process especially when implementing for multiple datapacks. Additionally, including version information in the message would only add to this, all while placing the responsibility of the useful information on each datapack developer rather than a single source.

One potential solution for this would be to use a storage based versioning. This allows for dynamic granular messaging without the overhead.

I have a prototype branch that makes use of registering with a JSON object and including fields such as datapack name, major version, minor version, and dependency datapacks. More details can be found [here](https://github.com/dthigpen/dtcraft-datapacks/tree/deptree/deptree) but in short the the above can be simplified down to the following,
```mcfunction
#load.mcfunction

data modify storage deptree:register info set value {name:"new_pack",major:0,minor:1, dependencies:[{name:"dep1"}, {name:"dep2", major:1}]}
function deptree:register

execute if data storage deptree:register loaded run schedule function new_pack:tick 1t replace
```

Providing the JSON object with the fields allows the `deptree:register` function to handle everything from error messaging to pack loading. Additional features could include author information and update url if provided by the originator.

Any feedback is greatly appreciated. I am content with keeping it as a separate pack and using it internally for my own packs but if the concept is of any value then I'd be happy to have it incorporated into Load.

**Comment by Luexa** [comment]
I agree that version resolution can be rather verbose, but I'm hesitant to add more functionality to the main pack. I've spoken with a number of my users and they seem to feel storage is a bit complex, and would rather Lantern Load be simple scoreboard w/ function tags like it is now. I did find some in favor of storage, but we couldn't come to a consensus on how the storage would be named. The root tag can't be overwritten or deleted with `data modify ... set`, so I would need to choose a sub-component of the storage, which means I would not only need to name the storage, but also an arbitrary subcomponent.

One issue I see is that the scoreboard and storage systems would not be trivially compatible, which means that a whole dependency tree will have to subscribe to the implementation instead of each pack being able to choose how they load. The whole reason I made Lantern Load was to avoid being put in situations where you would have to jump through extra hoops in the case that you depend on two libraries that each have their own loading process.

Additionally, there is a data pack collection that already performs its own error and diagnostic logging: [Gamemode 4](https://github.com/Gamemode4Dev/GM4_Datapacks). Assuming Gamemode 4 replaced some of its load process with deptree, there would now be two differently styled diagnostics: some would be in the Gamemode 4 style, and some would be in the deptree style. It would be confusing to end users to have diagnostics in the load process to be differently colored or have a different prefix from each other.

If it weren't for the above issues I'd probably be comfortable with making deptree an official "load extension". However, for more flexibility and thinner runtime code, I will likely select an implementation that uses a preprocessor to generate mcfunction code that sets scoreboards directly and can use a configurable logging system.

**Comment by dthigpen** [comment]
Very good points. Yeah I'd agree, it's likely best to keep it as lean and simple as possible especially given the constraints. I may look into some of the preprocessing options as well.

**Comment by Luexa** [comment]
I didn't really have time to suggest changes for every pack that uses LL, but most of the big users already know so hopefully it is alright. I need to merge this *now* so that people can use it to update their packs to 1.17.

**Pull request merged**
